COMPONENT_ADD_INCLUDEDIRS := .
COMPONENT_SRCDIRS := src

COMPONENT_EXTRA_INCLUDES := ./../wolfssl-esp32

COMPONENT_DEPENDS := wolfssl-esp32

CFLAGS +=  -Wno-maybe-uninitialized -DHAVE_ECC -DHAVE_AESGCM -DNO_FILESYSTEM